name: Pages

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-

      - name: Install dependencies
        run: npm install

      - name: Clean public directory
        run: rm -rf ./public

      - name: Build Hexo site
        run: npm run build

      - name: Print symlinks in public directory
        run: |
          echo "Symlinks in ./public (if any):"
          find ./public -type l -ls || true

      - name: Print public directory size
        run: du -sh ./public || true

      - name: Remove symlinks from public directory
        run: find ./public -type l -delete

      - name: Print files with multiple hard links in public directory
        run: |
          set -x
          echo "Checking for files with multiple hard links in ./public:"
          found=$(find ./public -type f -links +1 -ls)
          if [ -z "$found" ]; then
            echo "No files with multiple hard links found."
          else
            echo "$found"
          fi

      - name: Print special files in public directory
        run: |
          set -x
          echo "Checking for special files in ./public:"
          found=$(find ./public ! -type f ! -type d -ls)
          if [ -z "$found" ]; then
            echo "No special files found."
          else
            echo "$found"
          fi

      - name: Print hidden files in public directory
        run: |
          set -x
          echo "Checking for hidden files in ./public:"
          found=$(find ./public -name '.*' -ls)
          if [ -z "$found" ]; then
            echo "No hidden files found."
          else
            echo "$found"
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
